### ISSUE TITLE
Protection

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/FucksGiven#115]
Some users would like an option for the app to require a password or biometric input before opening.
I am not interested in this but a PR would be welcome of course.
Keep in mind that this feature will be [integrated into Google Play services](https://blog.google/products/android/android-theft-protection/) next year.

**Comment by Chetan-KH511** [comment]
Can I try?

**Comment by anuragkanojiya1** [comment]
@CrazyMarvin What about a login and signup activity so that each user is securely authenticated.
And for this authentication part we can use Firebase Auth.

If you are interested in this, assign me this issue and I will make a PR regarding this very soon.

**Comment by CrazyMarvin** [comment]
> @CrazyMarvin What about a login and signup activity so that each user is securely authenticated.
> And for this authentication part we can use Firebase Auth.
> 
> If you are interested in this, assign me this issue and I will make a PR regarding this very soon.

Thanks for your offer to help. 👍
The app is designed to be privacy-friendly and many users have de-Googled devices so Firebase is no option in this case. Everything should work offline and without proprietary components.

**Comment by anuragkanojiya1** [comment]
> > @CrazyMarvin What about a login and signup activity so that each user is securely authenticated.
> > And for this authentication part we can use Firebase Auth.
> > If you are interested in this, assign me this issue and I will make a PR regarding this very soon.
> 
> Thanks for your offer to help. 👍 The app is designed to be privacy-friendly and many users have de-Googled devices so Firebase is no option in this case. Everything should work offline and without proprietary components.

@CrazyMarvin So we can use Encrypted Shared Preferences then, to store the password with encryption and it will be offline too.

**Comment by CrazyMarvin** [comment]
> > > @CrazyMarvin What about a login and signup activity so that each user is securely authenticated.
> > > And for this authentication part we can use Firebase Auth.
> > > If you are interested in this, assign me this issue and I will make a PR regarding this very soon.
> > 
> > 
> > Thanks for your offer to help. 👍 The app is designed to be privacy-friendly and many users have de-Googled devices so Firebase is no option in this case. Everything should work offline and without proprietary components.
> 
> @CrazyMarvin So we can use Encrypted Shared Preferences then, to store the password with encryption and it will be offline too.

That's a good approach.
Additional to [Google Play](https://play.google/developer-distribution-agreement.html), we have to keep the [F-Droid policy](https://f-droid.org/en/docs/Inclusion_Policy/) in mind.

**Comment by anuragkanojiya1** [comment]
> > > > @CrazyMarvin What about a login and signup activity so that each user is securely authenticated.
> > > > And for this authentication part we can use Firebase Auth.
> > > > If you are interested in this, assign me this issue and I will make a PR regarding this very soon.
> > > 
> > > 
> > > Thanks for your offer to help. 👍 The app is designed to be privacy-friendly and many users have de-Googled devices so Firebase is no option in this case. Everything should work offline and without proprietary components.
> > 
> > 
> > @CrazyMarvin So we can use Encrypted Shared Preferences then, to store the password with encryption and it will be offline too.
> 
> That's a good approach. Additional to [Google Play](https://play.google/developer-distribution-agreement.html), we have to keep the [F-Droid policy](https://f-droid.org/en/docs/Inclusion_Policy/) in mind.

Yeah, google play and f-droid accepts this approach too.

**Comment by anuragkanojiya1** [comment]
@CrazyMarvin I've successfully implemented the Password Protection in the App's settings, I am currently working on the UI part, will send a video soon. 😊
