### ISSUE TITLE
Hosted Weblate Integration

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/FucksGiven#7]
@comradekingu suggests to use [Hosted Weblate](https://hosted.weblate.org/) for translations.

**Comment by CrazyMarvin** [comment]
Hosting request is sent. 😊

**Comment by comradekingu** [comment]
@CrazyMarvin 
https://hosted.weblate.org/projects/fucks-given/fucks-given/#information is locked
and the "kingu" account is not an admin in https://hosted.weblate.org/access/fucks-given/#users to do anything about it.

**Comment by CrazyMarvin** [comment]
Hosted Weblate is active and I donated a little amount to the awesome project. 😍
