### ISSUE TITLE
TODOs Before Public Release

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/FucksGiven#84]
- [x] Prepare both data_extraction_rules.xml files
- [x] Add Chromebook Screenshots (`fastlane/metadata/android/en-US/images/chromeBook/`)
- [x] Add 10-inch tablet screenshots (`fastlane/metadata/android/en-US/images/tenInchScreenshots/`)
- [x] Update strings.xml files
- [x] Add [Themed Icon](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive)
- [x] Get designer's approval
- [ ] Create trailer/app video

**Comment by mubeen1519** [comment]
everything is done and the string.xml looks fine as it is.

**Comment by CrazyMarvin** [comment]
> everything is done and the string.xml looks fine as it is.

Thank you so much!
