### ISSUE TITLE
Make Dark Mode Beautiful

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/FucksGiven#95]
The Dark Mode implementation is a bit ugly at the moment.
It would be nice if we could beautify it.

[Feedback](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15644#note_2081295908) from @linsui:
![feedback](https://github.com/user-attachments/assets/64a995e6-c4ca-4e0c-86aa-f94598a8fb83)

**Comment by yesseruser** [comment]
This is true.
![Screenshot_20240908-081838.png](https://github.com/user-attachments/assets/59e7e7f5-9944-43b2-9b87-d4b1b6f85f35)

![Screenshot_20240908-081831.png](https://github.com/user-attachments/assets/52140cec-0956-4dc2-9a38-b612b1a832ad)

![Screenshot_20240908-081835.png](https://github.com/user-attachments/assets/982a9c4e-0151-42f0-b879-731160ddf27a)

![Screenshot_20240908-081938.png](https://github.com/user-attachments/assets/b290f0f1-05cb-4f85-9f6a-bd8ad0760d8a)

**Comment by yesseruser** [comment]
[ ] The headers don't change.
[ ] The chart category (weekly/monthly/yearly) selected item doesn't change
[ ] The chart itself doesn't change

**Comment by CrazyMarvin** [comment]
Done in https://github.com/Crazy-Marvin/FucksGiven/pull/116.
