### ISSUE TITLE
Set today's date as default date

### ISSUE THREAD

**Issue by Aditya137x** [Crazy-Marvin/FucksGiven#97]
## :writing_hand: Describe the bug

If I don't select a date while adding an entry then the date default's to 1st Jan

## :bomb: Steps to reproduce

1. Click on plus symbol
2. Write description
3. Don't touch the "Select Date" optiob
4. Press Add
5. Entry gets created on 1 January

## :wrench: Expected behavior

Extry should get reflected on today's date if no date is selected

## :iphone: Tech info
- Device: 
- OS: Androud 14
- App Version: 1.0.2

**Comment by CrazyMarvin** [comment]
We plan to implement that.
@mubeen1519, may you prepare this for the next release?

**Comment by nok-ko** [comment]
I'm in the PDT timezone and setting the date to September 10 actually made the note show up on September 9 instead. :(

**Comment by guidomz** [comment]
I initially thought this was an intentional feature, as an additional lesson in patience, lol. But yes, an enhancement is best.

**Comment by CrazyMarvin** [comment]
Done in https://github.com/Crazy-Marvin/FucksGiven/pull/116.
