### ISSUE TITLE
Ability to edit an entry

### ISSUE THREAD

**Issue by Aditya137x** [Crazy-Marvin/FucksGiven#98]
Ability to edit an entry in case of some typo or wrong date selection.

**Comment by akashpal-21** [comment]
I wrote it down as another F given in the journal.

```
APP WONT LET ME EDIT THE ENTRY!!!! FFF
```

**Comment by CrazyMarvin** [comment]
> I wrote it down as another F given in the journal.
> 
> ```
> APP WONT LET ME EDIT THE ENTRY!!!! FFF
> ```

That was our goal. 🤣🤣
Jokes aside, editing an entry will be implemented.

**Comment by stefanboca** [comment]
IMHO, having the ability to delete entries would also be nice to have

**Comment by guidomz** [comment]
> I wrote it down as another F given in the journal.
> 
> ```
> APP WONT LET ME EDIT THE ENTRY!!!! FFF
> ```

LOL!

https://github.com/Crazy-Marvin/FucksGiven/issues/97#issuecomment-2367102215

**Comment by CrazyMarvin** [comment]
Done in https://github.com/Crazy-Marvin/FucksGiven/pull/116.
