### ISSUE TITLE
App Crashes Opening The Statistics

### ISSUE THREAD

**Issue by ninjazan420** [Crazy-Marvin/FucksGiven#99]
## :writing_hand: Describe the bug
If you click on statistics and there are no statistics available, the app crashes instantly

## :bomb: Steps to reproduce
1. Open app
2. Press on the bottom right icon if no recordings are available

## :wrench: Expected behavior
Show statistics or an empty error.

## :iphone: Tech info
- Device: Pixel 7 pro
- OS: 14 Stock
- App Version: 1.0.0

**Comment by Slautkn** [comment]
the same thing but I can't access the statistics no matter what I do even if there are statistics available.

**Comment by CrazyMarvin** [comment]
> the same thing but I can't access the statistics no matter what I do even if there are statistics available.

Which device are you using, @Slautkn?

On my Nothing Phone (1) running Android 14 the app closes when accessing the statistics. 
@mubeen1519 has no issues though.
We will contine to investiagate but any help would be deeply appreciated.

**Comment by Slautkn** [comment]
> > the same thing but I can't access the statistics no matter what I do even if there are statistics available.
> 
> Which device are you using, @Slautkn?
> 
> On my Nothing Phone (1) running Android 14 the app closes when accessing the statistics. @mubeen1519 has no issues though. We will contine to investiagate but any help would be deeply appreciated.

I have realme GT5 on Android 14

**Comment by mondlicht-und-sterne** [comment]
I use a Samsung S21 5G with Android 14.

I am experiencing the same phenomenon.

**Comment by mubeen1519** [comment]
please test the apk guys and let me know if it still crash
[FucksGiven-1.0.5-debug.zip](https://github.com/user-attachments/files/17257249/FucksGiven-1.0.5-debug.zip)

https://github.com/Crazy-Marvin/FucksGiven/pull/116

**Comment by mondlicht-und-sterne** [comment]
@mubeen1519 

the app still crashes for me

Samsung S21 5G
Android 14

**Comment by Slautkn** [comment]
> please test the apk guys and let me know if it still crash [FucksGiven-1.0.5-debug.zip](https://github.com/user-attachments/files/17257249/FucksGiven-1.0.5-debug.zip)
> 
> #116

Same for me the application launches well but when opening the statistics it crash

**Comment by CrazyMarvin** [comment]
On a Nothing phone (1) it still crashes when opening the statistics. I will send you a detailed Logcat, @mubeen1519.

**Comment by mubeen1519** [comment]
ok guyz here try once again with new apk hope so now issue is resolved 
[FucksGiven-1.0.5-debug.zip](https://github.com/user-attachments/files/17269522/FucksGiven-1.0.5-debug.zip)

**Comment by Slautkn** [comment]
> ok guyz here try once again with new apk hope so now issue is resolved [FucksGiven-1.0.5-debug.zip](https://github.com/user-attachments/files/17269522/FucksGiven-1.0.5-debug.zip)

It works perfectly for me thanks!

**Comment by CrazyMarvin** [comment]
It's working fine here too. I will create a new release. 
Thank you very much, @mubeen1519! 👍

**Comment by mondlicht-und-sterne** [comment]
it works on my Samsung S21 5G, Android 14, too.

Thank you so much.

![5195196895578940958](https://github.com/user-attachments/assets/3f990a21-8d27-411c-bad5-5c1ed0dd5ee9)

**Comment by ninjazan420** [comment]
Works perfectly fine now, thank you very much!

**Comment by garnetbugbee** [comment]
The debug file above also fixed my issue where I couldn't even input any of my fucks. I know I'm able to participate and the fun of this app.
